### ISSUE TITLE
Incorporate a go-back button on the bakery overview pages

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#10]
**Value Proposition**

**As a** potential customer
**I need** to navigate back to the [bakery page](https://github.com/barbigrade/capstone-project/issues/2)
**to** browse through other bakery menus because I'm indecisive

**Description**

![#5 back button](https://user-images.githubusercontent.com/107254671/192540769-2578fec5-020e-44ca-be6b-81bb407d6a64.png)

**Acceptance Criteria**
- [ ] The index page can be accessed through a snazzy button that signifies "go back"
- [ ] On click, the user is redirected back to the main page
- [ ] The button is displayed on each [bakery overview page](https://github.com/barbigrade/capstone-project/issues/3)

**Tasks**
- [ ] Create a back-button component and incorporate an icon that will signify it
- [ ] Use next/link to redirect the user back to the index page
- [ ] Update the [id].js file to build in the component
