### ISSUE TITLE
Create a shopping cart page (default state)

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#14]
**Value Proposition**

**As a** customer
**I need** to be able to put all the products I want to buy in one place
**to** be able to make the purchase quicker and easier at a later stage

**Description**

![#6 empty shopping cart page](https://user-images.githubusercontent.com/107254671/194031830-481a19d8-a787-4a44-8b56-60cf6fa4e29d.png)

**Acceptance Criteria**
- [ ] The shopping cart page is empty by default
- [ ] The body has a background image
- [ ] The page displays a message to signify that the cart is empty until the customer adds products to it
- [ ] A button is displayed below, leading back to the index page with the bakery list on click

**Tasks**
- [ ] Create a new page
- [ ] Create a button component and write logic to redirect the user back to the index page
- [ ] Create a component for the default shopping cart page

**Comment by Murci2022** [comment]
Hi there, great user story:)
