### ISSUE TITLE
Add toggle function and add to cart button

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#15]
**Value Proposition**

**As a** customer
**I need** to be able to select the items I want to buy
**to** be to add them to my shopping cart at a later stage

**Description**

![#7 add to cart button after toggle](https://user-images.githubusercontent.com/107254671/194045082-18c7c70d-faa4-4295-88dc-38a8fca9a0d0.png)

**Acceptance Criteria**
- [ ] On click, the product cards on each bakery overview page can be toggled to extend 
- [ ] The extended cards display an "add to cart" button
- [ ] When the product card is clicked again, the card returns to its default state with the button being hidden 

**Tasks**
- [ ] Create an "add to cart" button component (without functionality for the time being)
- [ ] Write toggle logic to extend the existing product card components
- [ ] Update the [id] page to implement both

**Comment by ben-me** [comment]
Hey, looks good to me except for these two sentences 😁 
> **to** be to add them to my shopping cart at a later stage
> On click, the product cards on each bakery overview page can be toggled to extend

One question about the tasks: I assume the Cards themselves are created from a component.
Why do you want to create the button as a seperate component instead of adding them to the existing card component (like you plan to do with the extension logic)?

**Comment by barbigrade** [comment]
Hey, thank you for looking this over! It's a great day for poor grammar and typos 😅

Re: the button component, I see what you mean. Initially, I thought it would make it easier to reuse the component elsewhere at a different point in time but your suggestion makes more sense I think :) Thanks again!

**Comment by ben-me** [comment]
There isn't really a right or wrong with the button component. If you need it outside of the cards then it's probably smarter to create a new component.
Just thought that if they are only available on the cards you could add them to the existing component.
