### ISSUE TITLE
Add to cart function

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#18]
**Value Proposition**

**As a** customer
**I need** to be able to add the items I want to buy to my shopping basket
**to** be able to purchase them at a later stage

**Description**

**Acceptance Criteria**
- [x] The shopping cart should be accessible from all pages through an icon in the header 
- [x] The "add to basket" button adds any selected item to the shopping cart page on click 

**Tasks**
- [x] Include the shopping basket icon in the header and link to the shopping cart page
- [x] Write add-to-cart logic for the existing product component using useState and product id
