### ISSUE TITLE
Create a list of bakeries

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#2]
**Value Proposition**

**As a** logged-in customer 
**I need** a list of available bakeries
**to be able to** browse through before selecting the one I'd like to order from

**Description**

![#1 bakery list dark](https://user-images.githubusercontent.com/107254671/190192756-f69e4032-caf4-4be4-86ad-55332e0631ce.png)

**Acceptance Criteria**
- [ ] A main header with the title of the app and a secondary one with the title of the section
- [ ] A card rendered for each bakery from the collection
- [ ] Each card displays a title, subtitle, price range, and score that in no way resembles the Wolt app. (Any resemblances are purely **accidental**.) 

**Tasks**
- [ ] Create a new feature branch
- [ ] Create a header component with an `h1` displaying the title of the app, and a section with an `h2` in which to insert the collection of bakeries
- [ ] Create a component for the collection of bakeries consisting of a `ul` and `li` elements for each one
- [ ] Dummy data should be used to render the list of bakeries with

**Comment by barbigrade** [comment]
Thanks, @MerleMak, for taking the time to review the user story and for the helpful feedback! I've updated it - please let me know if it needs any further adjustments :)

**Comment by MerleMak** [comment]
Perfect! Great Job Barbara!
