### ISSUE TITLE
Add total sum to the cart

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#20]
**Value Proposition**

**As a** customer
**I need** to be able to see the number of items and the total sum in my cart
**before** making my purchase

**Description**

![#9 counter](https://user-images.githubusercontent.com/107254671/195557670-41c6b28a-085b-4c92-98bf-9ba70ca4453c.png)

**Acceptance Criteria**
- [ ] The shopping basket should display a section with the number of items and the total sum

**Tasks**
- [ ] Create a counter function 
- [ ] Include quantity as a parameter within the cart
- [ ] Edit the data in the JSON file to be able to implement the above logic
