### ISSUE TITLE
Add styling

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#21]
**Value Proposition**

**As a** customer
**I need** an aesthetically pleasing and coherent interface
**to** use the app in an easy way while not being repulsed by its visuals

**Description**

**Acceptance Criteria**
- [ ] All components are coherently styled to support the functions of the app

**Tasks**
- [ ] Use Styled Components to pimp the pages and components of the app 
- [ ] Include images, icons, and data where missing
