### ISSUE TITLE
Create a bakery detail view page

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#3]
**Value Proposition**

**As a** potential customer
**I need** an overview of a single bakery
**to be able to** get more information and eventually browse through their menu

**Description**

![#2 bakery detail view](https://user-images.githubusercontent.com/107254671/190656099-0a4ae2e7-9732-42eb-872c-605d1b33040a.png)

**Acceptance Criteria**
- [ ] The facility detail view features a suitable image
- [ ] The name of the bakery and subtitle is displayed underneath the image
- [ ] A section with detail information is displayed below the name and subtitle
- [ ] The page is navigated by scrolling up and down

**Tasks**
- [ ] Create a new page
- [ ] Create a component for the bakery detail overview with an `h2` and `h3`, an image, paragraphs, and two sections. (The second section will be used to create a menu component at a later stage)
- [ ] Use details from the previously created JSON file to render the component

**Comment by MerleMak** [comment]
Hi Barbara!

Looks great! The only thing ist, that you could maybe specify "subtitle" 
But other than than, nothing to complain :)
Good job!
