### ISSUE TITLE
Add menu to each bakery overview page

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#4]
**Value Proposition**

**As a** potential customer
**I need** the menu of a single bakery
**to** browse through before I can select an item to order

**Description**

![#3 bakery menu view](https://user-images.githubusercontent.com/107254671/191205263-69f0749f-8937-4c90-85bd-ed3d729e7408.png)

**Acceptance Criteria**
- [ ] The menu for each bakery is displayed underneath the [bakery overview](https://github.com/barbigrade/capstone-project/issues/3#issue-1377529528)
- [ ] The menu is divided into a few product categories of which the name is displayed above each section
- [ ] Each product is showcased within a card with its own content: name, description, an image, and price
- [ ] The page is navigated by scrolling up and down

**Tasks**
- [ ] Create a component for the items on the menu 
- [ ] Add `h3`s that specify every product category
- [ ] Create sections to nestle each product category in
- [ ] Render each product card with an image, item name, description, and price
- [ ] Use details from the previously created JSON file to render the component

**Comment by barbigrade** [comment]
Hey @AnH13-6 - thanks so much for the helpful feedback! 
I'll definitely have a look to see how to divide the story into two smaller chunks and edit accordingly. Also great idea about the out-of-stock function - it would be cool to incorporate that in at a later stage for sure :)
