### ISSUE TITLE
Divide bakery menu into a few product categories

### ISSUE THREAD

**Issue by barbigrade** [barbigrade/capstone-project#8]
**Value Proposition**

**As a** potential customer
**I need** a better overview of each bakery menu
**to** browse through before I can select an item to order

**Description**

![#3 bakery menu view](https://user-images.githubusercontent.com/107254671/191205263-69f0749f-8937-4c90-85bd-ed3d729e7408.png)

**Acceptance Criteria**
- [ ] The menu is divided into a few product categories of which the name is displayed above each section
- [ ] The page is navigated by scrolling up and down

**Tasks**
- [ ] Update the menu component that displays the products each bakery offers 
- [ ] Add `h3`s that specify every product category
- [ ] Create sections to nestle each product category in
- [ ] Use details from the previously created JSON file to render the component
